project_id = "nkoogfznnqlnragbauez"

[functions.send-order-notifications]
verify_jwt = false

[functions.generate-pix]
verify_jwt = false

[functions.pix-webhook]
verify_jwt = false

[functions.check-pix-status]
verify_jwt = false

[functions.generate-boleto]
verify_jwt = false

[functions.boleto-webhook]
verify_jwt = false

[functions.process-credit-card]
verify_jwt = false

[functions.calculate-melhor-envio]
verify_jwt = false