project_id = "nkoogfznnqlnragbauez"

[functions.send-order-notifications]
verify_jwt = false

[functions.generate-pix]
verify_jwt = false

[functions.pix-webhook]
verify_jwt = false

[functions.check-pix-status]
verify_jwt = false

[functions.generate-boleto]
verify_jwt = false

[functions.boleto-webhook]
verify_jwt = false

[functions.process-credit-card]
verify_jwt = false

[functions.calculate-melhor-envio]
verify_jwt = false

[functions.send-landing-ticket-response]
verify_jwt = false

[functions.create-master-subscription]
verify_jwt = false

[functions.master-subscription-webhook]
verify_jwt = false

[functions.check-master-subscription-status]
verify_jwt = false

[functions.retry-master-payments]
verify_jwt = false

[functions.validate-card]
verify_jwt = false

[functions.ai-product-writer]
verify_jwt = false

[functions.media-presign]
verify_jwt = false
